mandatory_parameters:
  shop_path: /var/www/source
  shop_tests_path: vendor/oxid-esales/tests-deprecated-ce
  module_ids: 'osceasycredit'
optional_parameters:
  is_subshop: false
  install_shop: true
  restore_shop_after_tests_suite: false
  test_database_name: example
  restore_after_acceptance_tests: false
  restore_after_unit_tests: false
  activate_all_modules: false
  run_tests_for_shop: false
  run_tests_for_modules: true
  browser_name: firefox
  retry_times_after_test_fail: 2
