[{$smarty.block.parent}]
[{block name="email_plain_order_owner_easycredit_paymentplan"}]
    [{if $payment->oxuserpayments__oxpaymentsid->value == "easycreditinstallment"}]
        [{assign var="instalmentPaymentText" value=$order->getTilgungsplanTxt()}]
        [{if $instalmentPaymentText }]
            [{oxmultilang ident="OXPS_EASY_CREDIT_INSTALMENT_PLAN"}] [{$instalmentPaymentText}]
        [{/if}]
    [{/if}]
[{/block}]